(******************************************************************************
 * CUDA Driver API - Ctypes Type Definitions
 *
 * Pure OCaml bindings to CUDA driver API using ctypes.
 * No C stubs required - all FFI via ctypes-foreign.
 ******************************************************************************)

open Ctypes

(** {1 Basic Types} *)

(** CUDA device - integer handle *)
type cu_device = int

let cu_device : cu_device typ = int

(** Device pointer - 64-bit GPU memory address *)
type cu_deviceptr = Unsigned.uint64

let cu_deviceptr : cu_deviceptr typ = uint64_t

(** Size type for memory operations *)
let cu_size_t : Unsigned.size_t typ = size_t

(** {1 Opaque Handle Types} *)

(** CUDA context - opaque structure *)
type cu_context

let cu_context : cu_context structure typ = structure "CUctx_st"

let cu_context_ptr : cu_context structure ptr typ = ptr cu_context

(** CUDA module - compiled GPU code *)
type cu_module

let cu_module : cu_module structure typ = structure "CUmod_st"

let cu_module_ptr : cu_module structure ptr typ = ptr cu_module

(** CUDA function/kernel handle *)
type cu_function

let cu_function : cu_function structure typ = structure "CUfunc_st"

let cu_function_ptr : cu_function structure ptr typ = ptr cu_function

(** CUDA stream - async execution queue *)
type cu_stream

let cu_stream : cu_stream structure typ = structure "CUstream_st"

let cu_stream_ptr : cu_stream structure ptr typ = ptr cu_stream

(** CUDA event - synchronization primitive *)
type cu_event

let cu_event : cu_event structure typ = structure "CUevent_st"

let cu_event_ptr : cu_event structure ptr typ = ptr cu_event

(** {1 Result Codes} *)

type cu_result =
  | CUDA_SUCCESS
  | CUDA_ERROR_INVALID_VALUE
  | CUDA_ERROR_OUT_OF_MEMORY
  | CUDA_ERROR_NOT_INITIALIZED
  | CUDA_ERROR_DEINITIALIZED
  | CUDA_ERROR_PROFILER_DISABLED
  | CUDA_ERROR_PROFILER_NOT_INITIALIZED
  | CUDA_ERROR_PROFILER_ALREADY_STARTED
  | CUDA_ERROR_PROFILER_ALREADY_STOPPED
  | CUDA_ERROR_NO_DEVICE
  | CUDA_ERROR_INVALID_DEVICE
  | CUDA_ERROR_INVALID_IMAGE
  | CUDA_ERROR_INVALID_CONTEXT
  | CUDA_ERROR_CONTEXT_ALREADY_CURRENT
  | CUDA_ERROR_MAP_FAILED
  | CUDA_ERROR_UNMAP_FAILED
  | CUDA_ERROR_ARRAY_IS_MAPPED
  | CUDA_ERROR_ALREADY_MAPPED
  | CUDA_ERROR_NO_BINARY_FOR_GPU
  | CUDA_ERROR_ALREADY_ACQUIRED
  | CUDA_ERROR_NOT_MAPPED
  | CUDA_ERROR_NOT_MAPPED_AS_ARRAY
  | CUDA_ERROR_NOT_MAPPED_AS_POINTER
  | CUDA_ERROR_ECC_UNCORRECTABLE
  | CUDA_ERROR_UNSUPPORTED_LIMIT
  | CUDA_ERROR_CONTEXT_ALREADY_IN_USE
  | CUDA_ERROR_PEER_ACCESS_UNSUPPORTED
  | CUDA_ERROR_INVALID_PTX
  | CUDA_ERROR_INVALID_GRAPHICS_CONTEXT
  | CUDA_ERROR_INVALID_SOURCE
  | CUDA_ERROR_FILE_NOT_FOUND
  | CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND
  | CUDA_ERROR_SHARED_OBJECT_INIT_FAILED
  | CUDA_ERROR_OPERATING_SYSTEM
  | CUDA_ERROR_INVALID_HANDLE
  | CUDA_ERROR_NOT_FOUND
  | CUDA_ERROR_NOT_READY
  | CUDA_ERROR_ILLEGAL_ADDRESS
  | CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES
  | CUDA_ERROR_LAUNCH_TIMEOUT
  | CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING
  | CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED
  | CUDA_ERROR_PEER_ACCESS_NOT_ENABLED
  | CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE
  | CUDA_ERROR_CONTEXT_IS_DESTROYED
  | CUDA_ERROR_ASSERT
  | CUDA_ERROR_TOO_MANY_PEERS
  | CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED
  | CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED
  | CUDA_ERROR_HARDWARE_STACK_ERROR
  | CUDA_ERROR_ILLEGAL_INSTRUCTION
  | CUDA_ERROR_MISALIGNED_ADDRESS
  | CUDA_ERROR_INVALID_ADDRESS_SPACE
  | CUDA_ERROR_INVALID_PC
  | CUDA_ERROR_LAUNCH_FAILED
  | CUDA_ERROR_NOT_PERMITTED
  | CUDA_ERROR_NOT_SUPPORTED
  | CUDA_ERROR_UNKNOWN of int

let cu_result_of_int = function
  | 0 -> CUDA_SUCCESS
  | 1 -> CUDA_ERROR_INVALID_VALUE
  | 2 -> CUDA_ERROR_OUT_OF_MEMORY
  | 3 -> CUDA_ERROR_NOT_INITIALIZED
  | 4 -> CUDA_ERROR_DEINITIALIZED
  | 5 -> CUDA_ERROR_PROFILER_DISABLED
  | 6 -> CUDA_ERROR_PROFILER_NOT_INITIALIZED
  | 7 -> CUDA_ERROR_PROFILER_ALREADY_STARTED
  | 8 -> CUDA_ERROR_PROFILER_ALREADY_STOPPED
  | 100 -> CUDA_ERROR_NO_DEVICE
  | 101 -> CUDA_ERROR_INVALID_DEVICE
  | 200 -> CUDA_ERROR_INVALID_IMAGE
  | 201 -> CUDA_ERROR_INVALID_CONTEXT
  | 202 -> CUDA_ERROR_CONTEXT_ALREADY_CURRENT
  | 205 -> CUDA_ERROR_MAP_FAILED
  | 206 -> CUDA_ERROR_UNMAP_FAILED
  | 207 -> CUDA_ERROR_ARRAY_IS_MAPPED
  | 208 -> CUDA_ERROR_ALREADY_MAPPED
  | 209 -> CUDA_ERROR_NO_BINARY_FOR_GPU
  | 210 -> CUDA_ERROR_ALREADY_ACQUIRED
  | 211 -> CUDA_ERROR_NOT_MAPPED
  | 212 -> CUDA_ERROR_NOT_MAPPED_AS_ARRAY
  | 213 -> CUDA_ERROR_NOT_MAPPED_AS_POINTER
  | 214 -> CUDA_ERROR_ECC_UNCORRECTABLE
  | 215 -> CUDA_ERROR_UNSUPPORTED_LIMIT
  | 216 -> CUDA_ERROR_CONTEXT_ALREADY_IN_USE
  | 217 -> CUDA_ERROR_PEER_ACCESS_UNSUPPORTED
  | 218 -> CUDA_ERROR_INVALID_PTX
  | 219 -> CUDA_ERROR_INVALID_GRAPHICS_CONTEXT
  | 300 -> CUDA_ERROR_INVALID_SOURCE
  | 301 -> CUDA_ERROR_FILE_NOT_FOUND
  | 302 -> CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND
  | 303 -> CUDA_ERROR_SHARED_OBJECT_INIT_FAILED
  | 304 -> CUDA_ERROR_OPERATING_SYSTEM
  | 400 -> CUDA_ERROR_INVALID_HANDLE
  | 500 -> CUDA_ERROR_NOT_FOUND
  | 600 -> CUDA_ERROR_NOT_READY
  | 700 -> CUDA_ERROR_ILLEGAL_ADDRESS
  | 701 -> CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES
  | 702 -> CUDA_ERROR_LAUNCH_TIMEOUT
  | 703 -> CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING
  | 704 -> CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED
  | 705 -> CUDA_ERROR_PEER_ACCESS_NOT_ENABLED
  | 708 -> CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE
  | 709 -> CUDA_ERROR_CONTEXT_IS_DESTROYED
  | 710 -> CUDA_ERROR_ASSERT
  | 711 -> CUDA_ERROR_TOO_MANY_PEERS
  | 712 -> CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED
  | 713 -> CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED
  | 714 -> CUDA_ERROR_HARDWARE_STACK_ERROR
  | 715 -> CUDA_ERROR_ILLEGAL_INSTRUCTION
  | 716 -> CUDA_ERROR_MISALIGNED_ADDRESS
  | 717 -> CUDA_ERROR_INVALID_ADDRESS_SPACE
  | 718 -> CUDA_ERROR_INVALID_PC
  | 719 -> CUDA_ERROR_LAUNCH_FAILED
  | 800 -> CUDA_ERROR_NOT_PERMITTED
  | 801 -> CUDA_ERROR_NOT_SUPPORTED
  | n -> CUDA_ERROR_UNKNOWN n

let int_of_cu_result = function
  | CUDA_SUCCESS -> 0
  | CUDA_ERROR_INVALID_VALUE -> 1
  | CUDA_ERROR_OUT_OF_MEMORY -> 2
  | CUDA_ERROR_NOT_INITIALIZED -> 3
  | CUDA_ERROR_DEINITIALIZED -> 4
  | CUDA_ERROR_PROFILER_DISABLED -> 5
  | CUDA_ERROR_PROFILER_NOT_INITIALIZED -> 6
  | CUDA_ERROR_PROFILER_ALREADY_STARTED -> 7
  | CUDA_ERROR_PROFILER_ALREADY_STOPPED -> 8
  | CUDA_ERROR_NO_DEVICE -> 100
  | CUDA_ERROR_INVALID_DEVICE -> 101
  | CUDA_ERROR_INVALID_IMAGE -> 200
  | CUDA_ERROR_INVALID_CONTEXT -> 201
  | CUDA_ERROR_CONTEXT_ALREADY_CURRENT -> 202
  | CUDA_ERROR_MAP_FAILED -> 205
  | CUDA_ERROR_UNMAP_FAILED -> 206
  | CUDA_ERROR_ARRAY_IS_MAPPED -> 207
  | CUDA_ERROR_ALREADY_MAPPED -> 208
  | CUDA_ERROR_NO_BINARY_FOR_GPU -> 209
  | CUDA_ERROR_ALREADY_ACQUIRED -> 210
  | CUDA_ERROR_NOT_MAPPED -> 211
  | CUDA_ERROR_NOT_MAPPED_AS_ARRAY -> 212
  | CUDA_ERROR_NOT_MAPPED_AS_POINTER -> 213
  | CUDA_ERROR_ECC_UNCORRECTABLE -> 214
  | CUDA_ERROR_UNSUPPORTED_LIMIT -> 215
  | CUDA_ERROR_CONTEXT_ALREADY_IN_USE -> 216
  | CUDA_ERROR_PEER_ACCESS_UNSUPPORTED -> 217
  | CUDA_ERROR_INVALID_PTX -> 218
  | CUDA_ERROR_INVALID_GRAPHICS_CONTEXT -> 219
  | CUDA_ERROR_INVALID_SOURCE -> 300
  | CUDA_ERROR_FILE_NOT_FOUND -> 301
  | CUDA_ERROR_SHARED_OBJECT_SYMBOL_NOT_FOUND -> 302
  | CUDA_ERROR_SHARED_OBJECT_INIT_FAILED -> 303
  | CUDA_ERROR_OPERATING_SYSTEM -> 304
  | CUDA_ERROR_INVALID_HANDLE -> 400
  | CUDA_ERROR_NOT_FOUND -> 500
  | CUDA_ERROR_NOT_READY -> 600
  | CUDA_ERROR_ILLEGAL_ADDRESS -> 700
  | CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES -> 701
  | CUDA_ERROR_LAUNCH_TIMEOUT -> 702
  | CUDA_ERROR_LAUNCH_INCOMPATIBLE_TEXTURING -> 703
  | CUDA_ERROR_PEER_ACCESS_ALREADY_ENABLED -> 704
  | CUDA_ERROR_PEER_ACCESS_NOT_ENABLED -> 705
  | CUDA_ERROR_PRIMARY_CONTEXT_ACTIVE -> 708
  | CUDA_ERROR_CONTEXT_IS_DESTROYED -> 709
  | CUDA_ERROR_ASSERT -> 710
  | CUDA_ERROR_TOO_MANY_PEERS -> 711
  | CUDA_ERROR_HOST_MEMORY_ALREADY_REGISTERED -> 712
  | CUDA_ERROR_HOST_MEMORY_NOT_REGISTERED -> 713
  | CUDA_ERROR_HARDWARE_STACK_ERROR -> 714
  | CUDA_ERROR_ILLEGAL_INSTRUCTION -> 715
  | CUDA_ERROR_MISALIGNED_ADDRESS -> 716
  | CUDA_ERROR_INVALID_ADDRESS_SPACE -> 717
  | CUDA_ERROR_INVALID_PC -> 718
  | CUDA_ERROR_LAUNCH_FAILED -> 719
  | CUDA_ERROR_NOT_PERMITTED -> 800
  | CUDA_ERROR_NOT_SUPPORTED -> 801
  | CUDA_ERROR_UNKNOWN n -> n

let cu_result : cu_result typ =
  view ~read:cu_result_of_int ~write:int_of_cu_result int

(** {1 Device Attributes} *)

type cu_device_attribute =
  | CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK
  | CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X
  | CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y
  | CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z
  | CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X
  | CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y
  | CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z
  | CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK
  | CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY
  | CU_DEVICE_ATTRIBUTE_WARP_SIZE
  | CU_DEVICE_ATTRIBUTE_MAX_PITCH
  | CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK
  | CU_DEVICE_ATTRIBUTE_CLOCK_RATE
  | CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT
  | CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT
  | CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT
  | CU_DEVICE_ATTRIBUTE_INTEGRATED
  | CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY
  | CU_DEVICE_ATTRIBUTE_COMPUTE_MODE
  | CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR
  | CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR
  | CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR
  | CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT
  | CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING
  | CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR
  | CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY
  | CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD
  | CU_DEVICE_ATTRIBUTE_OTHER of int

let int_of_device_attribute = function
  | CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK -> 1
  | CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X -> 2
  | CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y -> 3
  | CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z -> 4
  | CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X -> 5
  | CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y -> 6
  | CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z -> 7
  | CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK -> 8
  | CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY -> 9
  | CU_DEVICE_ATTRIBUTE_WARP_SIZE -> 10
  | CU_DEVICE_ATTRIBUTE_MAX_PITCH -> 11
  | CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK -> 12
  | CU_DEVICE_ATTRIBUTE_CLOCK_RATE -> 13
  | CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT -> 14
  | CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT -> 16
  | CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT -> 17
  | CU_DEVICE_ATTRIBUTE_INTEGRATED -> 18
  | CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY -> 19
  | CU_DEVICE_ATTRIBUTE_COMPUTE_MODE -> 20
  | CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR -> 75
  | CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR -> 76
  | CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR -> 39
  | CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT -> 40
  | CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING -> 41
  | CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR -> 81
  | CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY -> 83
  | CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD -> 84
  | CU_DEVICE_ATTRIBUTE_OTHER n -> n

(** {1 Context Flags} *)

let cu_ctx_sched_auto = 0x00

let cu_ctx_sched_spin = 0x01

let cu_ctx_sched_yield = 0x02

let cu_ctx_sched_blocking_sync = 0x04

let cu_ctx_map_host = 0x08

let cu_ctx_lmem_resize_to_max = 0x10

(** {1 Memory Copy Kinds} *)

type cu_memcpy_kind =
  | CU_MEMCPY_HOST_TO_HOST
  | CU_MEMCPY_HOST_TO_DEVICE
  | CU_MEMCPY_DEVICE_TO_HOST
  | CU_MEMCPY_DEVICE_TO_DEVICE
  | CU_MEMCPY_DEFAULT

let int_of_memcpy_kind = function
  | CU_MEMCPY_HOST_TO_HOST -> 0
  | CU_MEMCPY_HOST_TO_DEVICE -> 1
  | CU_MEMCPY_DEVICE_TO_HOST -> 2
  | CU_MEMCPY_DEVICE_TO_DEVICE -> 3
  | CU_MEMCPY_DEFAULT -> 4

(** {1 Event Flags} *)

let cu_event_default = 0x0

let cu_event_blocking_sync = 0x1

let cu_event_disable_timing = 0x2

let cu_event_interprocess = 0x4

(** {1 Stream Flags} *)

let cu_stream_default = 0x0

let cu_stream_non_blocking = 0x1

(** {1 JIT Options} *)

type cu_jit_option =
  | CU_JIT_MAX_REGISTERS
  | CU_JIT_THREADS_PER_BLOCK
  | CU_JIT_WALL_TIME
  | CU_JIT_INFO_LOG_BUFFER
  | CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES
  | CU_JIT_ERROR_LOG_BUFFER
  | CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES
  | CU_JIT_OPTIMIZATION_LEVEL
  | CU_JIT_TARGET_FROM_CUCONTEXT
  | CU_JIT_TARGET
  | CU_JIT_FALLBACK_STRATEGY
  | CU_JIT_GENERATE_DEBUG_INFO
  | CU_JIT_LOG_VERBOSE
  | CU_JIT_GENERATE_LINE_INFO
  | CU_JIT_CACHE_MODE

let int_of_jit_option = function
  | CU_JIT_MAX_REGISTERS -> 0
  | CU_JIT_THREADS_PER_BLOCK -> 1
  | CU_JIT_WALL_TIME -> 2
  | CU_JIT_INFO_LOG_BUFFER -> 3
  | CU_JIT_INFO_LOG_BUFFER_SIZE_BYTES -> 4
  | CU_JIT_ERROR_LOG_BUFFER -> 5
  | CU_JIT_ERROR_LOG_BUFFER_SIZE_BYTES -> 6
  | CU_JIT_OPTIMIZATION_LEVEL -> 7
  | CU_JIT_TARGET_FROM_CUCONTEXT -> 8
  | CU_JIT_TARGET -> 9
  | CU_JIT_FALLBACK_STRATEGY -> 10
  | CU_JIT_GENERATE_DEBUG_INFO -> 11
  | CU_JIT_LOG_VERBOSE -> 12
  | CU_JIT_GENERATE_LINE_INFO -> 13
  | CU_JIT_CACHE_MODE -> 14

(** {1 Function Attributes} *)

type cu_function_attribute =
  | CU_FUNC_ATTRIBUTE_MAX_THREADS_PER_BLOCK
  | CU_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES
  | CU_FUNC_ATTRIBUTE_CONST_SIZE_BYTES
  | CU_FUNC_ATTRIBUTE_LOCAL_SIZE_BYTES
  | CU_FUNC_ATTRIBUTE_NUM_REGS
  | CU_FUNC_ATTRIBUTE_PTX_VERSION
  | CU_FUNC_ATTRIBUTE_BINARY_VERSION
  | CU_FUNC_ATTRIBUTE_CACHE_MODE_CA

let int_of_func_attribute = function
  | CU_FUNC_ATTRIBUTE_MAX_THREADS_PER_BLOCK -> 0
  | CU_FUNC_ATTRIBUTE_SHARED_SIZE_BYTES -> 1
  | CU_FUNC_ATTRIBUTE_CONST_SIZE_BYTES -> 2
  | CU_FUNC_ATTRIBUTE_LOCAL_SIZE_BYTES -> 3
  | CU_FUNC_ATTRIBUTE_NUM_REGS -> 4
  | CU_FUNC_ATTRIBUTE_PTX_VERSION -> 5
  | CU_FUNC_ATTRIBUTE_BINARY_VERSION -> 6
  | CU_FUNC_ATTRIBUTE_CACHE_MODE_CA -> 7

(** {1 Helper: Result to string} *)

let string_of_cu_result = function
  | CUDA_SUCCESS -> "CUDA_SUCCESS"
  | CUDA_ERROR_INVALID_VALUE -> "CUDA_ERROR_INVALID_VALUE"
  | CUDA_ERROR_OUT_OF_MEMORY -> "CUDA_ERROR_OUT_OF_MEMORY"
  | CUDA_ERROR_NOT_INITIALIZED -> "CUDA_ERROR_NOT_INITIALIZED"
  | CUDA_ERROR_DEINITIALIZED -> "CUDA_ERROR_DEINITIALIZED"
  | CUDA_ERROR_NO_DEVICE -> "CUDA_ERROR_NO_DEVICE"
  | CUDA_ERROR_INVALID_DEVICE -> "CUDA_ERROR_INVALID_DEVICE"
  | CUDA_ERROR_INVALID_CONTEXT -> "CUDA_ERROR_INVALID_CONTEXT"
  | CUDA_ERROR_INVALID_HANDLE -> "CUDA_ERROR_INVALID_HANDLE"
  | CUDA_ERROR_NOT_FOUND -> "CUDA_ERROR_NOT_FOUND"
  | CUDA_ERROR_NOT_READY -> "CUDA_ERROR_NOT_READY"
  | CUDA_ERROR_LAUNCH_FAILED -> "CUDA_ERROR_LAUNCH_FAILED"
  | CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES -> "CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES"
  | CUDA_ERROR_INVALID_PTX -> "CUDA_ERROR_INVALID_PTX"
  | CUDA_ERROR_UNKNOWN n -> Printf.sprintf "CUDA_ERROR_UNKNOWN(%d)" n
  | _ -> "CUDA_ERROR_OTHER"
